### ISSUE TITLE
`minio/minio-go/v7@v7.0.67/utils.go:627:67: undefined: tls.CertificateVerificationError` with Go 1.19.

### ISSUE THREAD

**Issue by simondeziel** [minio/minio-go#1931]
https://github.com/minio/minio-go/pull/1921 and more specifically https://github.com/minio/minio-go/commit/76a41461fe5124fb9b646615c6abafcd1d41c7c2 caused minio-go to no longer build with Go 1.19.

**Comment by harshavardhana** [comment]
https://endoflife.date/go go1.19 is EOLed

**Comment by simondeziel** [comment]
@harshavardhana I guess a mention on https://github.com/minio/minio-go/releases/tag/v7.0.67 would have avoid the surprise on our side. I'm fine with dropping support for EOL Go version but was thrown off by `go 1.17` in the [`go.mod`](https://github.com/minio/minio-go/blob/master/go.mod#L3).

**Comment by harshavardhana** [comment]
go1.17 was kept for migration purposes; it was a mistake when using the new types.

**Comment by haorenfsa** [comment]
Agree! We run into this issue as well. If we're still going use go1.17 in go mod, then better fix it. otherwise better update it to 1.20

**Comment by mahbubzulkarnain** [comment]
Upgrade version golang, solve for me. go 1.20
