### ISSUE TITLE
build fails: "undefined: randString"

### ISSUE THREAD

**Issue by legrostdg** [minio/minio-go#685]
I'm trying to update the Debian package of `minio-go` to 2.1.0. The build seems to fail:

    	go test -v -p 4 github.com/minio/minio-go github.com/minio/minio-go/pkg/encrypt github.com/minio/minio-go/pkg/policy github.com/minio/minio-go/pkg/s3signer github.com/minio/minio-go/pkg/s3utils github.com/minio/minio-go/pkg/set
    # github.com/minio/minio-go
    src/github.com/minio/minio-go/core_test.go:59: undefined: randString
    src/github.com/minio/minio-go/core_test.go:71: undefined: randString
    src/github.com/minio/minio-go/core_test.go:233: undefined: randString
    src/github.com/minio/minio-go/core_test.go:296: undefined: randString
    src/github.com/minio/minio-go/core_test.go:315: undefined: randString
    FAIL	github.com/minio/minio-go [build failed]
    ?   	github.com/minio/minio-go/pkg/encrypt	[no test files]
    === RUN   TestConditionKeyMapAdd
    --- PASS: TestConditionKeyMapAdd (0.00s)
    === RUN   TestConditionKeyMapRemove
    --- PASS: TestConditionKeyMapRemove (0.00s)
    === RUN   TestConditionKeyMapRemoveKey
    --- PASS: TestConditionKeyMapRemoveKey (0.00s)
    === RUN   TestCopyConditionKeyMap
    --- PASS: TestCopyConditionKeyMap (0.00s)
    === RUN   TestMergeConditionKeyMap
    --- PASS: TestMergeConditionKeyMap (0.00s)
    === RUN   TestConditionMapAdd
    --- PASS: TestConditionMapAdd (0.00s)
    === RUN   TestConditionMapRemove
    --- PASS: TestConditionMapRemove (0.00s)
    === RUN   TestMergeConditionMap
    --- PASS: TestMergeConditionMap (0.00s)
    === RUN   TestIsValidStatement
    --- PASS: TestIsValidStatement (0.00s)
    === RUN   TestNewStatements
    --- PASS: TestNewStatements (0.00s)
    === RUN   TestGetInUsePolicy
    --- PASS: TestGetInUsePolicy (0.00s)
    === RUN   TestRemoveStatements
    --- PASS: TestRemoveStatements (0.00s)
    === RUN   TestAppendStatement
    --- PASS: TestAppendStatement (0.00s)
    === RUN   TestGetBucketPolicy
    --- PASS: TestGetBucketPolicy (0.00s)
    === RUN   TestGetObjectPolicy
    --- PASS: TestGetObjectPolicy (0.00s)
    === RUN   TestListBucketPolicies
    --- PASS: TestListBucketPolicies (0.00s)
    === RUN   TestGetPolicy
    --- PASS: TestGetPolicy (0.00s)
    === RUN   TestSetPolicy
    --- PASS: TestSetPolicy (0.00s)
    === RUN   TestIsValidBucketPolicy
    --- PASS: TestIsValidBucketPolicy (0.00s)
    === RUN   TestBucketPolicyResourceMatch
    --- PASS: TestBucketPolicyResourceMatch (0.00s)
    PASS
    ok  	github.com/minio/minio-go/pkg/policy	0.005s
    === RUN   TestGetSeedSignature
    --- PASS: TestGetSeedSignature (0.00s)
    === RUN   TestChunkSignature
    --- PASS: TestChunkSignature (0.00s)
    === RUN   TestSetStreamingAuthorization
    --- PASS: TestSetStreamingAuthorization (0.00s)
    === RUN   TestStreamingReader
    --- PASS: TestStreamingReader (0.00s)
    === RUN   TestResourceListSorting
    --- PASS: TestResourceListSorting (0.00s)
    === RUN   TestSignatureCalculation
    --- PASS: TestSignatureCalculation (0.00s)
    === RUN   TestEncodeURL2Path
    --- PASS: TestEncodeURL2Path (0.00s)
    PASS
    ok  	github.com/minio/minio-go/pkg/s3signer	0.011s
    === RUN   TestIsValidDomain
    --- PASS: TestIsValidDomain (0.00s)
    === RUN   TestIsValidIP
    --- PASS: TestIsValidIP (0.00s)
    === RUN   TestIsVirtualHostSupported
    --- PASS: TestIsVirtualHostSupported (0.00s)
    === RUN   TestIsAmazonEndpoint
    --- PASS: TestIsAmazonEndpoint (0.00s)
    === RUN   TestIsAmazonChinaEndpoint
    --- PASS: TestIsAmazonChinaEndpoint (0.00s)
    === RUN   TestIsGoogleEndpoint
    --- PASS: TestIsGoogleEndpoint (0.00s)
    === RUN   TestPercentEncodeSlash
    --- PASS: TestPercentEncodeSlash (0.00s)
    === RUN   TestQueryEncode
    --- PASS: TestQueryEncode (0.00s)
    === RUN   TestEncodePath
    --- PASS: TestEncodePath (0.00s)
    PASS
    ok  	github.com/minio/minio-go/pkg/s3utils	0.007s
    === RUN   TestNewStringSet
    --- PASS: TestNewStringSet (0.00s)
    === RUN   TestCreateStringSet
    --- PASS: TestCreateStringSet (0.00s)
    === RUN   TestCopyStringSet
    --- PASS: TestCopyStringSet (0.00s)
    === RUN   TestStringSetAdd
    --- PASS: TestStringSetAdd (0.00s)
    === RUN   TestStringSetRemove
    --- PASS: TestStringSetRemove (0.00s)
    === RUN   TestStringSetContains
    --- PASS: TestStringSetContains (0.00s)
    === RUN   TestStringSetFuncMatch
    --- PASS: TestStringSetFuncMatch (0.00s)
    === RUN   TestStringSetApplyFunc
    --- PASS: TestStringSetApplyFunc (0.00s)
    === RUN   TestStringSetEquals
    --- PASS: TestStringSetEquals (0.00s)
    === RUN   TestStringSetIntersection
    --- PASS: TestStringSetIntersection (0.00s)
    === RUN   TestStringSetDifference
    --- PASS: TestStringSetDifference (0.00s)
    === RUN   TestStringSetUnion
    --- PASS: TestStringSetUnion (0.00s)
    === RUN   TestStringSetMarshalJSON
    --- PASS: TestStringSetMarshalJSON (0.00s)
    === RUN   TestStringSetUnmarshalJSON
    --- PASS: TestStringSetUnmarshalJSON (0.00s)
    === RUN   TestStringSetString
    --- PASS: TestStringSetString (0.00s)
    === RUN   TestStringSetToSlice
    --- PASS: TestStringSetToSlice (0.00s)
    PASS
    ok  	github.com/minio/minio-go/pkg/set	0.012s

Do you have an idea of what is going on?

**Comment by harshavardhana** [comment]
Build works fine locally for me and on the CI. how are you trying to build what is your go version ?

**Comment by legrostdg** [comment]
go version: 1.7.4

I'm building the package with a custom Debian tool, called dh-golang. It calls `go test -v -p 4 github.com/minio/minio-go github.com/minio/minio-go/pkg/encrypt github.com/minio/minio-go/pkg/policy github.com/minio/minio-go/pkg/s3signer github.com/minio/minio-go/pkg/s3utils github.com/minio/minio-go/pkg/set` which seems to fail:

    src/github.com/minio/minio-go/core_test.go:59: undefined: randString
    src/github.com/minio/minio-go/core_test.go:71: undefined: randString
    src/github.com/minio/minio-go/core_test.go:233: undefined: randString
    src/github.com/minio/minio-go/core_test.go:296: undefined: randString
    src/github.com/minio/minio-go/core_test.go:315: undefined: randString

**Comment by vadmeste** [comment]
Build on 2.1.0 also works fine for me.

@legrostdg is your package removing some files from the origin source code? randString is defined here api_functional_v4_test.go

**Comment by harshavardhana** [comment]
> @legrostdg is your package removing some files from the origin source code? randString is defined here api_functional_v4_test.go

I think dh-golang is trying to remove some tests from top level since they are functional tests and cannot be tested..  Can you share your debian config would love to see what scripts that are being run.

**Comment by legrostdg** [comment]
The source for `minio-go` is available there: https://anonscm.debian.org/git/pkg-go/packages/golang-github-minio-minio-go.git

`dh-golang` source: https://anonscm.debian.org/git/pkg-go/packages/dh-golang.git

**Comment by legrostdg** [comment]
OK, I think I got it: `api_functional_v4_test.go` is removed from the build, because it tries to access s3.amazonaws.com, which is not allowed by Debian policy... Would it be possible to move the function somewhere else?

**Comment by vadmeste** [comment]
@legrostdg yes, we can. By the way, if you pass `-short` flag to `go test` , no server will be contacted, will that work for you?

**Comment by legrostdg** [comment]
I didn't noted this '-short' flag. It is exactly what we needed, except the unintuitive name (-nonetwork or something else would have been better) :-). Thanks!

**Comment by vadmeste** [comment]
:+1:
