### ISSUE TITLE
make fails due to unit test failure in TestCoreCopyObject 

### ISSUE THREAD

**Issue by krisis** [minio/minio-go#1044]
```
--- FAIL: TestCoreCopyObject (1.06s)
	core_test.go:433: Error: expected etag to be same as source object 7515e2ca2f78be0c2437f3fb674412c6, but found different etag :d41d8cd98f00b204e9800998ecf8427e
=== RUN   TestCoreCopyObjectPart

```

**Comment by kannappanr** [comment]
The unit test is fine. There is a regression introduce in commit https://github.com/minio/minio/commit/5f6d717b7aeafe14ba6f2fc2a9cc765b5fe9ad7d

Which is now fixed by, https://github.com/minio/minio/pull/6868

**Comment by noideawhatimdoinghere** [comment]
Getting the same error on latest release of minio:

```
--- FAIL: TestCoreCopyObject (0.02s)
    core_test.go:440: Error: expected etag to be same as source object 85d7cf88a69e504d8a55855047b9d570-1, but found different etag :89b630bea8ec4f150f8f3ff7f07459bc-1
```

```git log``` shows:
```
commit 33aec08e8c918c21a1d117f1de3f3ce6cf942768 (HEAD -> master, origin/master, origin/HEAD)
Author: Klaus Post <klauspost@gmail.com>
Date:   Fri Sep 6 14:57:55 2019 -0700

    Clean up go. mod (#8197)
    
    Golang proposes to clean up these and is fairly insisting about it ;)

commit 5bde31d021b49955d97ab84b90bd22d4e0521307
Author: Minio Trusted <trusted@minio.io>
Date:   Thu Sep 5 23:30:40 2019 +0000

    Update yaml files to latest version RELEASE.2019-09-05T23-24-38Z

commit b52a3e523cc3c4debc0ea2f86386377df5355c81 (tag: RELEASE.2019-09-05T23-24-38Z)
Author: Harshavardhana <harsha@minio.io>
Date:   Thu Sep 5 15:51:27 2019 -0700

    Avoid using fastjson parser pool, move back to jsoniter (#8190)
    
    It looks like from implementation point of view fastjson
    parser pool doesn't behave the same way as expected
    when dealing many `xl.json` from multiple disks.
    
    The fastjson parser pool usage ends up returning incorrect
    xl.json entries for checksums, with references pointing
    to older entries. This led to the subtle bug where checksum
    info is duplicated from a previous xl.json read of a different
    file from different disk.

commit 428836d4e1952f176aa7e5c0515b047b6d812d64
Author: Praveen raj Mani <praveen@minio.io>
Date:   Fri Sep 6 02:25:48 2019 +0530

    Ignore "connection reset" errors while initializing the targets with queue store enabled (#8185)
    
    Fixes #8178


```

**Comment by harshavardhana** [comment]
ETag is not supposed to be same anymore @noideawhatimdoinghere . We have tests running every PR. We don't see this issue.

**Comment by brentadamson** [comment]
Why does the test fail with the latest version, then?

**Comment by noideawhatimdoinghere** [comment]
The tests pass if I download the binary like travis does: ```curl -O https://dl.minio.io/server/minio/release/linux-amd64/minio && chmod +x ./minio``` BUT I get an error in minio server ```Error: Bad digest: Expected d41d8cd98f00b204e9800998ecf8427e is not valid with what we calculated 7515e2ca2f78be0c2437f3fb674412c6```. Something isn't right

**Comment by noideawhatimdoinghere** [comment]
That binary seems to use commit ```b52a3e523cc3c4debc0ea2f86386377df5355c81``` but then if I revert my local repo to that same hash then the test fails AND I get the the "bad digest" error in the server log. I'm trying to figure out what I'm doing wrong...

**Comment by harshavardhana** [comment]
Why can't you use the binary if it works ?

**Comment by noideawhatimdoinghere** [comment]
Why would the binary be any different than running it directly? It indicates there is an issue in the build process. Besides, the binary gives that error.

**Comment by harshavardhana** [comment]
I don't think that is true. There is an issue in your build process @noideawhatimdoinghere . We are running the same tests for each PR. 

I have not access to you build env. So I suggest you use binary now and explain your build process in a different GitHub issue we will take a look.

**Comment by noideawhatimdoinghere** [comment]
Ok. It probably is something I'm doing wrong. Will open new issue
